
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    data-username: root
    data-password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    database: MYSQL
    show-sql: true

server:
  port: 0